import type { NavigatorYearPlan } from "@/types/navigator";

/** Fictional sample for sales/marketing demos — not a real family's data. */
export const sampleReportMeta = {
  studentName: "Emma",
  age: "11",
  startingGrade: "6th",
  horizon: "7 years until 12th-grade graduation",
  yearsCharted: 7,
  subjectsPerYear: 5,
  choicesPerSubject: 3,
  price: "$77",
  priceNote: "one-time — not a subscription",
  tagline: "Not one year. Every year until graduation.",
  subtitle:
    "A sample Homeschool Lighthouse Navigator chart showing how one academic interview profile becomes a full multi-year voyage — three trusted curriculum choices per subject, for every remaining school year through Senior year.",
  privacyNote:
    "In a real purchase, personal answers stay password-protected in the family's account and are never sold or marketed to companies.",
  ctaHref: "/navigator",
  ctaLabel: "Get The Navigator for your family",
} as const;

const site = "https://homeschoollighthouse.com";

function choice(
  rank: 1 | 2 | 3,
  title: string,
  company: string,
  slug: string,
  listingType: string,
  format: string,
  creditHint: string,
  reason: string,
) {
  return {
    rank,
    title,
    company,
    slug,
    href: `${site}/listing/${slug}`,
    listingType,
    format,
    creditHint,
    reason,
    websiteUrl: `https://www.example.com/${slug}`,
  };
}

/** Condensed sample: full 7-year voyage with 2 subjects shown deeply for sales clarity. */
export const sampleYearPlans: NavigatorYearPlan[] = [
  {
    yearIndex: 1,
    gradeLevel: "6th",
    gradeLabel: "6th grade",
    ageHint: "About age 11 · Middle-school bridge year",
    subjectPlans: [
      {
        subjectKey: "english",
        subjectLabel: "English / Language Arts / Reading",
        recommendedCredits: "Full-year ELA · builds toward high school credits",
        libertyNote: "Middle years bridge elementary literacy into high school–ready writing.",
        choices: [
          choice(
            1,
            "IEW-style Writing Foundations for Middle Grades",
            "Institute for Excellence in Writing",
            "iew-writing-foundations-sample",
            "curriculum",
            "in_home",
            "Full-year ELA · builds toward high school credits",
            "parent-led · reading/writing friendly · strong structure",
          ),
          choice(
            2,
            "Living Literature & Composition Pathway",
            "Sonlight",
            "sonlight-lit-comp-sample",
            "curriculum",
            "hybrid",
            "Full-year ELA · builds toward high school credits",
            "book-rich · faith-friendly option · self-paced friendly",
          ),
          choice(
            3,
            "Digital Language Arts with Instructor Feedback",
            "Time4Learning",
            "time4learning-ela-sample",
            "online_course",
            "online",
            "Full-year ELA · builds toward high school credits",
            "online delivery · instructor-supported · flexible pacing",
          ),
        ],
      },
      {
        subjectKey: "math",
        subjectLabel: "Mathematics",
        recommendedCredits: "Full-year math · pre-algebra path when ready",
        libertyNote: "Middle years often prepare pre-algebra / Algebra I readiness.",
        choices: [
          choice(
            1,
            "Pre-Algebra Readiness with Manipulatives",
            "Math-U-See",
            "math-u-see-prealgebra-sample",
            "curriculum",
            "in_home",
            "Full-year math · pre-algebra path when ready",
            "kinesthetic-friendly · parent-led · mastery paced",
          ),
          choice(
            2,
            "Saxon-Aligned Middle Math Sequence",
            "Rainbow Resource",
            "saxon-middle-math-sample",
            "curriculum",
            "hybrid",
            "Full-year math · pre-algebra path when ready",
            "incremental review · budget-aware · paper/offline friendly",
          ),
          choice(
            3,
            "Interactive Online Middle Math",
            "Khan Academy",
            "khan-middle-math-sample",
            "online_course",
            "online",
            "Full-year math · pre-algebra path when ready",
            "free/budget-friendly · tech-forward · self-paced",
          ),
        ],
      },
    ],
  },
  {
    yearIndex: 2,
    gradeLevel: "7th",
    gradeLabel: "7th grade",
    ageHint: "About age 12 · Middle-school bridge year",
    subjectPlans: [
      {
        subjectKey: "english",
        subjectLabel: "English / Language Arts / Reading",
        recommendedCredits: "Full-year ELA · builds toward high school credits",
        choices: [
          choice(
            1,
            "Essay Building & Literature Discussion",
            "Institute for Excellence in Writing",
            "iew-essay-building-sample",
            "curriculum",
            "in_home",
            "Full-year ELA · builds toward high school credits",
            "writing level growth · parent grading ready",
          ),
          choice(
            2,
            "World Literature Reader Set",
            "The Good and the Beautiful",
            "tgtb-world-lit-sample",
            "curriculum",
            "in_home",
            "Full-year ELA · builds toward high school credits",
            "gentle beauty · paper/offline · family shared reading",
          ),
          choice(
            3,
            "Online Writing Workshop (Middle)",
            "Outschool",
            "outschool-writing-middle-sample",
            "online_course",
            "online",
            "Full-year ELA · builds toward high school credits",
            "instructor-graded · live class option · social learners",
          ),
        ],
      },
      {
        subjectKey: "science",
        subjectLabel: "Science",
        recommendedCredits: "Full-year science · labs when possible",
        choices: [
          choice(
            1,
            "General Science with Notebooking Labs",
            "Apologia",
            "apologia-general-science-sample",
            "curriculum",
            "hybrid",
            "Full-year science · labs when possible",
            "faith-based option · lab habits · parent-led",
          ),
          choice(
            2,
            "Hands-On Life Science Investigations",
            "Elemental Science",
            "elemental-life-science-sample",
            "curriculum",
            "in_home",
            "Full-year science · labs when possible",
            "kinesthetic · observation-rich · notebooking",
          ),
          choice(
            3,
            "Interactive Middle Science Course",
            "Time4Learning",
            "time4learning-science-sample",
            "online_course",
            "online",
            "Full-year science · labs when possible",
            "online delivery · flexible · tech-balanced",
          ),
        ],
      },
    ],
  },
  {
    yearIndex: 3,
    gradeLevel: "8th",
    gradeLabel: "8th grade",
    ageHint: "About age 13 · Final middle-school year before credits",
    subjectPlans: [
      {
        subjectKey: "math",
        subjectLabel: "Mathematics",
        recommendedCredits: "Full-year math · pre-algebra path when ready",
        choices: [
          choice(
            1,
            "Pre-Algebra / Algebra Readiness",
            "Math-U-See",
            "math-u-see-algebra-readiness-sample",
            "curriculum",
            "in_home",
            "Full-year math · pre-algebra path when ready",
            "mastery · video lessons · parent-led",
          ),
          choice(
            2,
            "Algebra Prep Worktexts",
            "BJU Press",
            "bju-algebra-prep-sample",
            "curriculum",
            "hybrid",
            "Full-year math · pre-algebra path when ready",
            "structured · faith-friendly · clear scope",
          ),
          choice(
            3,
            "Online Pre-Algebra Academy",
            "Teaching Textbooks",
            "teaching-textbooks-prealg-sample",
            "online_course",
            "online",
            "Full-year math · pre-algebra path when ready",
            "automated grading · independent learners",
          ),
        ],
      },
      {
        subjectKey: "history",
        subjectLabel: "History / Social Studies",
        recommendedCredits: "Full-year history / civics",
        choices: [
          choice(
            1,
            "American & World History Story Spine",
            "Mystery of History",
            "mystery-of-history-sample",
            "curriculum",
            "in_home",
            "Full-year history / civics",
            "chronological · reading-rich · family discussion",
          ),
          choice(
            2,
            "Civics & Geography Foundations",
            "Notgrass History",
            "notgrass-civics-sample",
            "curriculum",
            "hybrid",
            "Full-year history / civics",
            "primary sources · faith-friendly · writing tie-ins",
          ),
          choice(
            3,
            "Interactive History Path",
            "Time4Learning",
            "time4learning-history-sample",
            "online_course",
            "online",
            "Full-year history / civics",
            "online · quizzes · flexible pacing",
          ),
        ],
      },
    ],
  },
  {
    yearIndex: 4,
    gradeLevel: "9th",
    gradeLabel: "9th — Freshman",
    ageHint: "About age 14 · High school credit year 1 of 4",
    subjectPlans: [
      {
        subjectKey: "english",
        subjectLabel: "English / Language Arts / Reading",
        recommendedCredits: "1.0 credit / year · aim for 4 total",
        libertyNote:
          "Often 4 units of English for competitive college admission (e.g. Liberty University).",
        choices: [
          choice(
            1,
            "English I with Literature & Composition",
            "BJU Press",
            "bju-english-i-sample",
            "curriculum",
            "hybrid",
            "1.0 credit / year · aim for 4 total",
            "credit-ready · instructor or parent grading options",
          ),
          choice(
            2,
            "Excellence in Writing — High School Continuum",
            "Institute for Excellence in Writing",
            "iew-hs-english-sample",
            "curriculum",
            "in_home",
            "1.0 credit / year · aim for 4 total",
            "essay strength · parent-led · college-bound writing",
          ),
          choice(
            3,
            "Online English I with Teacher",
            "Bridgeway Academy",
            "bridgeway-english-i-sample",
            "online_course",
            "online",
            "1.0 credit / year · aim for 4 total",
            "instructor-graded · transcript support",
          ),
        ],
      },
      {
        subjectKey: "math",
        subjectLabel: "Mathematics",
        recommendedCredits: "1.0 credit / year · aim for 3–4 total",
        libertyNote: "Often 3–4 units of mathematics through Algebra II or beyond.",
        choices: [
          choice(
            1,
            "Algebra I",
            "Math-U-See",
            "math-u-see-algebra-i-sample",
            "curriculum",
            "in_home",
            "1.0 credit / year · aim for 3–4 total",
            "credit-bearing · mastery · video support",
          ),
          choice(
            2,
            "Algebra I Dual-Support Course",
            "Teaching Textbooks",
            "teaching-textbooks-algebra-i-sample",
            "online_course",
            "online",
            "1.0 credit / year · aim for 3–4 total",
            "automatic grading · independent HS pacing",
          ),
          choice(
            3,
            "Algebra I Homeschool Kit",
            "Abeka",
            "abeka-algebra-i-sample",
            "curriculum",
            "hybrid",
            "1.0 credit / year · aim for 3–4 total",
            "structured · faith-based · clear daily lessons",
          ),
        ],
      },
    ],
  },
  {
    yearIndex: 5,
    gradeLevel: "10th",
    gradeLabel: "10th — Sophomore",
    ageHint: "About age 15 · High school credit year 2 of 4",
    subjectPlans: [
      {
        subjectKey: "science",
        subjectLabel: "Science",
        recommendedCredits: "1.0 lab credit / year · aim for 3 total",
        libertyNote: "Often 3 lab science units (biology, chemistry, physics preferred).",
        choices: [
          choice(
            1,
            "Biology with Lab",
            "Apologia",
            "apologia-biology-sample",
            "curriculum",
            "hybrid",
            "1.0 lab credit / year · aim for 3 total",
            "lab credit path · faith-based · college-bound",
          ),
          choice(
            2,
            "Biology Online with Labs",
            "BJU Press",
            "bju-biology-online-sample",
            "online_course",
            "online",
            "1.0 lab credit / year · aim for 3 total",
            "instructor option · structured labs",
          ),
          choice(
            3,
            "Biology Textbook + Lab Kit Bundle",
            "Rainbow Resource",
            "rainbow-biology-kit-sample",
            "supplement",
            "in_home",
            "1.0 lab credit / year · aim for 3 total",
            "budget-flexible · parent-led labs",
          ),
        ],
      },
      {
        subjectKey: "history",
        subjectLabel: "History / Social Studies",
        recommendedCredits: "1.0 credit / year · aim for 3 total",
        libertyNote:
          "Often 3 social studies / history units, including U.S. history & government.",
        choices: [
          choice(
            1,
            "World History Credit Course",
            "Notgrass History",
            "notgrass-world-history-sample",
            "curriculum",
            "in_home",
            "1.0 credit / year · aim for 3 total",
            "credit-ready · reading & writing integrated",
          ),
          choice(
            2,
            "World History Online",
            "Abeka",
            "abeka-world-history-sample",
            "online_course",
            "online",
            "1.0 credit / year · aim for 3 total",
            "structured · faith-based · video lessons",
          ),
          choice(
            3,
            "History & Geography Dual Track",
            "BJU Press",
            "bju-world-history-sample",
            "curriculum",
            "hybrid",
            "1.0 credit / year · aim for 3 total",
            "college-prep tone · clear assessments",
          ),
        ],
      },
    ],
  },
  {
    yearIndex: 6,
    gradeLevel: "11th",
    gradeLabel: "11th — Junior",
    ageHint: "About age 16 · High school credit year 3 of 4",
    subjectPlans: [
      {
        subjectKey: "english",
        subjectLabel: "English / Language Arts / Reading",
        recommendedCredits: "1.0 credit / year · aim for 4 total",
        choices: [
          choice(
            1,
            "American Literature & Composition",
            "BJU Press",
            "bju-american-lit-sample",
            "curriculum",
            "hybrid",
            "1.0 credit / year · aim for 4 total",
            "junior-year depth · essay & research growth",
          ),
          choice(
            2,
            "College-Prep Writing Seminar",
            "Institute for Excellence in Writing",
            "iew-college-prep-sample",
            "curriculum",
            "in_home",
            "1.0 credit / year · aim for 4 total",
            "advanced writing · parent or tutor grading",
          ),
          choice(
            3,
            "Online American Lit with Teacher",
            "Bridgeway Academy",
            "bridgeway-american-lit-sample",
            "online_course",
            "online",
            "1.0 credit / year · aim for 4 total",
            "instructor-graded · transcript-ready",
          ),
        ],
      },
      {
        subjectKey: "math",
        subjectLabel: "Mathematics",
        recommendedCredits: "1.0 credit / year · aim for 3–4 total",
        choices: [
          choice(
            1,
            "Algebra II",
            "Math-U-See",
            "math-u-see-algebra-ii-sample",
            "curriculum",
            "in_home",
            "1.0 credit / year · aim for 3–4 total",
            "credit path · mastery · video lessons",
          ),
          choice(
            2,
            "Algebra II Online",
            "Teaching Textbooks",
            "teaching-textbooks-algebra-ii-sample",
            "online_course",
            "online",
            "1.0 credit / year · aim for 3–4 total",
            "auto-grading · independent junior year",
          ),
          choice(
            3,
            "Algebra II Homeschool Kit",
            "Abeka",
            "abeka-algebra-ii-sample",
            "curriculum",
            "hybrid",
            "1.0 credit / year · aim for 3–4 total",
            "structured daily lessons · faith-based",
          ),
        ],
      },
    ],
  },
  {
    yearIndex: 7,
    gradeLevel: "12th",
    gradeLabel: "12th — Senior",
    ageHint: "About age 17 · Graduation year",
    subjectPlans: [
      {
        subjectKey: "english",
        subjectLabel: "English / Language Arts / Reading",
        recommendedCredits: "1.0 credit / year · aim for 4 total",
        libertyNote:
          "Often 4 units of English for competitive college admission (e.g. Liberty University).",
        choices: [
          choice(
            1,
            "British Literature & Senior Thesis Prep",
            "BJU Press",
            "bju-british-lit-sample",
            "curriculum",
            "hybrid",
            "1.0 credit / year · aim for 4 total",
            "senior capstone writing · college admissions ready",
          ),
          choice(
            2,
            "College Composition Bridge",
            "Institute for Excellence in Writing",
            "iew-college-comp-sample",
            "curriculum",
            "in_home",
            "1.0 credit / year · aim for 4 total",
            "research essays · parent or dual-enrollment style",
          ),
          choice(
            3,
            "Online Senior English with Teacher",
            "Bridgeway Academy",
            "bridgeway-senior-english-sample",
            "online_course",
            "online",
            "1.0 credit / year · aim for 4 total",
            "instructor-graded · final transcript support",
          ),
        ],
      },
      {
        subjectKey: "science",
        subjectLabel: "Science",
        recommendedCredits: "1.0 lab credit / year · aim for 3 total",
        libertyNote: "Often 3 lab science units (biology, chemistry, physics preferred).",
        choices: [
          choice(
            1,
            "Chemistry or Physics Lab Credit",
            "Apologia",
            "apologia-chemistry-sample",
            "curriculum",
            "hybrid",
            "1.0 lab credit / year · aim for 3 total",
            "lab science credit · college-bound STEM option",
          ),
          choice(
            2,
            "Chemistry Online with Labs",
            "BJU Press",
            "bju-chemistry-sample",
            "online_course",
            "online",
            "1.0 lab credit / year · aim for 3 total",
            "instructor support · structured assessments",
          ),
          choice(
            3,
            "Conceptual Physics / Chemistry Kit",
            "Rainbow Resource",
            "rainbow-physics-chem-sample",
            "supplement",
            "in_home",
            "1.0 lab credit / year · aim for 3 total",
            "hands-on labs · parent-led · flexible budget",
          ),
        ],
      },
    ],
  },
];

export const sampleVoyageSummary = [
  { grade: "6th", focus: "Bridge literacy & pre-algebra readiness" },
  { grade: "7th", focus: "Writing stamina + hands-on science" },
  { grade: "8th", focus: "Algebra readiness + civics foundations" },
  { grade: "9th", focus: "English I & Algebra I credits begin" },
  { grade: "10th", focus: "Lab biology + world history credits" },
  { grade: "11th", focus: "American lit + Algebra II" },
  { grade: "12th", focus: "Senior English + final lab science → graduation" },
] as const;
